# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Minecraft Mod with Gradle

on:
  push:
    branches: [ master , main]
  pull_request:
    branches: [ master, main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x *
    - name: Install unzip
      run: sudo apt install unzip
    - name: Build with Gradle
      run: |
        wget http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-mdk.zip
        unzip -n ./forge-1.12.2-14.23.5.2847-mdk.zip
        ./gradlew setupdecompworkspace
        ./gradlew build
